version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
    groups:
      dev:
        patterns: ["pytest*", "ruff", "mypy", "tox", "pre-commit"]
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
